CREATE ROLE codehub
WITH
    LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD 'Codehub';

CREATE TABLE users (
    id SERIAL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO users (name) VALUES ("Test");

GRANT pg_read_all_stats TO codehub;

GRANT INSERT,
SELECT, DELETE,
UPDATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO codehub;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO codehub;